services:
  - type: web
    name: product-manager
    env: docker
    buildCommand: docker build -t product-manager .
    startCommand: docker run -p 8080:8080 product-manager
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"